### ISSUE TITLE
Convert google-http-java-client/google-http-client-jackson2/ to be based on gson

### ISSUE THREAD

**Issue by elharo** [googleapis/google-http-java-client#1208]
Per go/json-madness

I *think* that despite the name of the package, the Jackson dependencies are purely internal so we should be able to swap this out without breaking anything.

**Comment by chingor13** [comment]
The `JsonFactory` implementations are provided in separate, interchangeable artifacts. This core library itself does not depend on either Jackson or Gson, but to use the JSON serialization/deserialization features, you need to pick one and configure it (likely whatever you are already using in your project).

**Comment by elharo** [comment]
We could probably make JacksonFactory a shim over GsonFactory unless there's a reason someone actually needs to pick Jackson as the parser.

**Comment by elharo** [comment]
Tentatively not going to do this right now.

**Comment by gregjotau** [comment]
Jackson 3 makes the interchangeable-artifact approach relevant again. Jackson 3 uses the `tools.jackson` packages and requires Java 17, while applications on frameworks such as Spring Boot 4 may already have Jackson 3 on the classpath. Today those applications must either add Gson or retain Jackson 2 solely for this adapter.

Would the maintainers be open to a separate `google-http-client-jackson3` artifact compiled for Java 17, while leaving the existing Java 8 artifacts unchanged? If that direction is acceptable, I would be happy to follow the contribution process and work on the implementation. Otherwise, is Gson intended to remain the recommended option for Jackson 3 applications?
