### ISSUE TITLE
There is no proxy authentication

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-http-java-client#190]
_From [ogregoire](https://code.google.com/u/ogregoire/) on January 11, 2013 01:56:14_

Version of google-http-java-client (e.g. 1.5.0-beta)? 1.13.1-beta Java environment (e.g. Java 6, Android 2.3, App Engine)? Java 7 Describe the problem. I want my application to be able to access APIs behind a proxy that requires an authentication, but no proxy authentication is available. It is possible to set the proxy, but not to authenticate to it. How would you expect it to be fixed? Some parameters in the (Apache|Net)HttpTransport.Builder class should be set so we can use a proxy with authentication along with the proxy setting.

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=190_

**Comment by chanseokoh** [comment]
@ajaaym please reopen. I have no permission to do so. As the original feature request says, this is about proxy authentication and not about setting proxy. The Oracle guide you linked just explains ways to set proxy. However, it does not say anything about setting up *proxy authentication*.

However, we did find some way to set up proxy authentication by directly controlling Apache HttpClient, which Google HTTP Client depends on: https://github.com/GoogleContainerTools/jib/pull/1337 and https://github.com/GoogleContainerTools/jib/pull/1366

**Comment by ajaaym** [comment]
@chanseokoh Please look at this [answer](https://stackoverflow.com/questions/1626549/authenticated-http-proxy-with-java) sorry I forgot to add link about this in previous comment. Please let me know if this still doesn't work.

**Comment by chanseokoh** [comment]
The accepted answer in the SO is to replace the single global `Authenticator` instance that affects everyone on a JVM, which is often infeasible to adopt, e.g., in a multi-threadedd application, plugin environment, etc., where you do not wholely own or control the entite JVM. I think what is required is each individual Google HTTP client instance being able to flexibly and independently configure proxies and their auth, not modifying a global state JVM-wise or affecting each other. Does it make sense?

**Comment by chanseokoh** [comment]
Reopen?

**Comment by ajaaym** [comment]
@chanseokoh this library uses Jre provided transport. Can you please describe your use case in more detail, which doesn't seems normal? This can also be achieved by using Proxy-Authroization header as described [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Proxy-Authorization) use [HttpRequestInitializer](https://github.com/googleapis/google-http-java-client/blob/master/google-http-client/src/main/java/com/google/api/client/http/HttpRequestInitializer.java)

**Comment by chanseokoh** [comment]
Thanks for opening this.

> which doesn't seems normal?

I don't think my use case is unusual. The accepted answer in the SO just can't be used in multi-thread environment. (Agreed?) I am sure you will get that a multi-thread application is a normal use case. Also, as I said, the answer affects everyone on a JVM globally, which is not acceptable if you are developing, say a plugin where your code runs on a larger framework/platform, e.g., an IDE plugin separately installable into the IDE.

> this library uses Jre provided transport.

I don't think this matters. IMO, the library should be able to send `Proxy-Authorization` (when required), e.g., even if no proxy-related system properties such as `http.proxyHost` are defined, or even if the JRE transport did not have any support for proxy. With Google HTTP client, I think I should be able to send `Proxy-Authorization` by calling some library API methods, and currently, you do have some API interface through which users can set proxies. From what I see, it is just that you don't yet have the API to set proxy auth.

For example, you do have [`ApacheHttpTransport.setProxy()`](https://github.com/googleapis/google-http-java-client/blob/release-1.25.0/google-http-client/src/main/java/com/google/api/client/http/apache/ApacheHttpTransport.java#L287`]), and [`ApacheHttpTransport.setProxySelector()`](https://github.com/googleapis/google-http-java-client/blob/release-1.25.0/google-http-client/src/main/java/com/google/api/client/http/apache/ApacheHttpTransport.java#L305). However, there's no API to set proxy auth. I *think* `ApacheHttpTransport` could add such methods. But there may be other places where these kinds of proxy methods would fit in too.

> This can also be achieved by using Proxy-Authroization header as described here use HttpRequestInitializer

Sure, you can do whatever you want to achieve by directly and manually crafting HTTP headers at a low level, but then there would be no point of creating a HTTP library whose purpose is to provide high-level abstraction for ease of use and convenience, if the user has to manually do tedious low-level HTTP header manipulation. For example, according to your argument, what's the point of having methods such as [`.setAuthorization()`](https://github.com/googleapis/google-http-java-client/blob/master/google-http-client/src/main/java/com/google/api/client/http/HttpHeaders.java#L254) as a library, given that you can set whatever header you want with `HttpRequestInitializer`? (Sorry, this is a rhetorical question.) Also note that, using `HttpRequestInitializer` will be very tedious if `ProxySelector` is configured to, say, connect to different proxies based on hosts.

As a side note, `HttpHeaders` doesn't have `Proxy-Authorization`: https://github.com/googleapis/google-http-java-client/blob/master/google-http-client/src/main/java/com/google/api/client/http/HttpHeaders.java#L59. I wonder if it makes sense to add it too.

And, given that `ApacheHttpTransport` already has `setProxy()` and `setProxySelector()`, which already implemented some proxy support in it instead of delegating proxy support to JRE, I do think someone at Google did want to add first-class proxy support in the library. So, I think it should expand to complete the proxy support (i.e., add proxy auth support).

Sorry this was long, but I hope this makes things clear (for me too).

**Comment by chingor13** [comment]
In google-http-client 1.28.0, you will be able to actually use a modern Apache HttpClient implementation which supports proxy authentication. It will be available via google-http-client-apache (2.0.0). The ApacheHttpTransport will no longer crash with unsupported method exceptions when providing your own implementation as we removed dependence upon deprecated methods.

**Comment by charlesportwood** [comment]
@chingor13 How do you use ApacheHttpTransport to configure proxy authentication? I have GMAIL service accounts and I need to build them with configured proxy authentication.

**Comment by mjovanc** [comment]
I'm not sure this is relevant to this issue. But currently I experiencing issues such as "Failed to select a proxy". Isn't it possible without it?
