### ISSUE TITLE
Performance: Drive.files().insert() performs much slower than implementing upload using Drive.getRequestFactory()

### ISSUE THREAD

**Issue by siom79** [googleapis/google-http-java-client#284]
The following invocation of `Drive.files().insert()` is significantly slower than implementing the same functionality using the `HttpRequestFactory` directly.

Sample for `Drive.files().insert()`:

```
Drive.Files.Insert insert = drive.files().insert(remoteFile, new InputStreamContent(remoteFile.getMimeType(), finalInputStream));
```

Sample for the `HttpRequestFactory` approach:

```
GenericUrl url = new GenericUrl("https://www.googleapis.com/upload/drive/v2/files?uploadType=media");
HttpContent content = new HttpContent() {
    @Override
    public long getLength() throws IOException {
        return localFile.length();
    }

    @Override
    public String getType() {
        return mimeType;
    }

    @Override
    public boolean retrySupported() {
        return false;
    }

    @Override
    public void writeTo(OutputStream out) throws IOException {
        FileInputStream fis = new FileInputStream(localFile);
        byte[] buffer = new byte[16*1024];
        int read = fis.read(buffer);
        while (read != -1) {
            out.write(buffer, 0, read);
            read = fis.read(buffer);
        }
    }
};
JsonHttpContent metadataContent = new JsonHttpContent(drive.getJsonFactory(), remoteFile);
MultipartContent multipartContent = new MultipartContent().setContentParts(Arrays.asList(metadataContent, content));
HttpRequest httpRequest = drive.getRequestFactory().buildPostRequest(url, multipartContent);
HttpResponse httpResponse = httpRequest.execute();
int statusCode = httpResponse.getStatusCode();
if (statusCode == HttpStatusCodes.STATUS_CODE_OK) {
    httpRequest.setParser(drive.getObjectParser());
    return httpResponse.parseAs(File.class);
}
```

The same is true when using resumable uploads as described [here](https://developers.google.com/drive/web/manage-uploads#resumable) using the `HttpRequestFactory`.

**Comment by andrey-qlogic** [comment]
@siom79, @ajaaym 
When you use insert (for v2) or create (for create v3) as you described below
```
Drive.Files.Insert insert = drive.files().insert(remoteFile, new InputStreamContent(remoteFile.getMimeType(), finalInputStream));
```
you may want to set the flag **directUploadEnabled** to true which is false by default 
```
insert.getMediaHttpUploader().setDirectUploadEnabled(true);
```
In this case, the direct upload will be used with exactly the same approach as you described.

Please take a look at the code of HttpMediaUploader Please take a look at the HttpMediaUploader upload method https://github.com/googleapis/google-api-java-client/blob/dd801893c4d6ab730870a58e711bc9dd3e5cf668/google-api-client/src/main/java/com/google/api/client/googleapis/media/MediaHttpUploader.java#L330


You also may want to disable gzip content encoding to increase throughput
```
create.setDisableGZipContent(true);
```
As it was fixed in https://github.com/googleapis/google-cloud-java/issues/3822
